embeddings {
  tensor_name: "embedding:0"
  metadata_path: "E:/anaconda3_file/projectBN_2/projector/projector/metadata.tsv"
  sprite {
    image_path: "E:/anaconda3_file/projectBN_2/projector/data/mnist_10k_sprite.png"
    single_image_dim: 28
    single_image_dim: 28
  }
}
